
services:
  backend:
    container_name: yourname-backend
    restart: always
    command: /app/start.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=host.docker.internal
